#:include '../src/real_kinds.fypp'
#:set PROGRAM_NAME = 'check_dp_5_dx'
program ${PROGRAM_NAME}$

  use, intrinsic :: iso_fortran_env, only: error_unit
  #:for REAL_KIND in REAL_KINDS
  use, intrinsic :: iso_fortran_env, only: ${REAL_KIND}$
  #:endfor

  use, intrinsic :: ieee_arithmetic, only: ieee_next_after

  use, non_intrinsic :: legendre_polynomial_recurrence_fortran



  implicit none



  integer, parameter :: num_trials = 10000



  #:for REAL_KIND in REAL_KINDS
  call ${PROGRAM_NAME}$_${REAL_KIND}$()
  #:endfor

  print *, 'OK: ${PROGRAM_NAME}$'



  contains


  #:for REAL_KIND in REAL_KINDS

  #:set SUBROUTINE_NAME = PROGRAM_NAME + '_' + REAL_KIND
  subroutine ${SUBROUTINE_NAME}$()

    real(${REAL_KIND}$), parameter :: rel_tol = epsilon(1.0_${REAL_KIND}$) * 26.0_${REAL_KIND}$


    integer :: i

    real(${REAL_KIND}$) :: dp_5_dx, dp_5_dx_ref, abs_dp_5_dx_dif

    real(${REAL_KIND}$) :: tolerance

    real(${REAL_KIND}$) :: x, x2

    type(legendre_polynomial_with_derivative_${REAL_KIND}$_type) :: lp


    call initialize_prng

    call lp%set(5)


    do i = 1, num_trials

      call random_number(x) ! [0, 1)

      x = 2.0_${REAL_KIND}$ * x - 1.0_${REAL_KIND}$ ! [-1, 1)

      x2 = x * x

      dp_5_dx_ref = 1.875_${REAL_KIND}$ * ( (21.0_${REAL_KIND}$ * x2 - 14.0_${REAL_KIND}$) * x2 + 1.0_${REAL_KIND}$ )

      call lp%set(x)

      call lp%evaluate()

      dp_5_dx = lp%dp_n_dx()

      abs_dp_5_dx_dif = abs(dp_5_dx - dp_5_dx_ref)
      tolerance   = rel_tol * max(abs(dp_5_dx_ref), 1.0_${REAL_KIND}$)

      if (abs_dp_5_dx_dif > tolerance) then

        write(error_unit, *) 'x               : ', x
        write(error_unit, *) 'dp_5_dx     (x) : ', dp_5_dx
        write(error_unit, *) 'dp_5_dx_ref (x) : ', dp_5_dx_ref
        write(error_unit, *) 'diff            : ', abs_dp_5_dx_dif
        write(error_unit, *) 'tolerance       : ', tolerance
        write(error_unit, *) 'dp_5_dx differs from the reference beyond the tolerance.'

        error stop

      end if

    end do

  end subroutine ${SUBROUTINE_NAME}$
  #:del SUBROUTINE_NAME

  #:endfor


  subroutine initialize_prng

    integer :: i, seed_size

    integer, allocatable :: seed(:)

    call random_seed(size=seed_size)

    allocate( seed(seed_size) )

    do i = 1, seed_size
      seed(i) = i
    end do

    call random_seed( put = seed(:) )

  end subroutine

end program ${PROGRAM_NAME}$
