#:include '../src/real_kinds.fypp'
#:set PROGRAM_NAME = 'check_p_0'
program ${PROGRAM_NAME}$

  use, intrinsic :: iso_fortran_env, only: error_unit
  #:for REAL_KIND in REAL_KINDS
  use, intrinsic :: iso_fortran_env, only: ${REAL_KIND}$
  #:endfor

  use, intrinsic :: ieee_arithmetic, only: ieee_next_after

  use, non_intrinsic :: legendre_polynomial_recurrence_fortran



  implicit none



  integer, parameter :: num_trials = 100


  #:for REAL_KIND in REAL_KINDS

  call ${PROGRAM_NAME}$_${REAL_KIND}$( &!
    one_next_before = ieee_next_after(1.0_${REAL_KIND}$, 0.0_${REAL_KIND}$) , &!
    one_next_after  = ieee_next_after(1.0_${REAL_KIND}$, 2.0_${REAL_KIND}$)   &!
  )

  #:endfor

  print *, 'OK: ${PROGRAM_NAME}$'



  contains


  #:for REAL_KIND in REAL_KINDS

  #:set SUBROUTINE_NAME = PROGRAM_NAME + '_' + REAL_KIND
  subroutine ${SUBROUTINE_NAME}$(one_next_before, one_next_after)

    real(${REAL_KIND}$), intent(in) :: one_next_before, one_next_after


    integer :: i

    real(${REAL_KIND}$) :: p_0, x

    type(legendre_polynomial_${REAL_KIND}$_type) :: lp


    call initialize_prng

    call lp%set(0)


    do i = 1, num_trials

      call random_number(x) ! [0, 1)

      x = 2.0_${REAL_KIND}$ * x - 1.0_${REAL_KIND}$ ! [-1, 1)

      call lp%set(x)

      call lp%evaluate()

      p_0 = lp%p_n()

      if (p_0 < one_next_before) then

        write(error_unit, *) 'x               : ', x
        write(error_unit, *) 'one_next_before : ', one_next_before
        write(error_unit, *) 'p_0 was less than 1.'

        error stop

      else if (p_0 > one_next_after) then

        write(error_unit, *) 'one_next_after : ', one_next_after
        write(error_unit, *) 'x              : ', x
        write(error_unit, *) 'p_0 was greater than 1.'

        error stop

      end if

    end do

  end subroutine ${SUBROUTINE_NAME}$
  #:del SUBROUTINE_NAME

  #:endfor


  subroutine initialize_prng

    integer :: i, seed_size

    integer, allocatable :: seed(:)

    call random_seed(size=seed_size)

    allocate( seed(seed_size) )

    do i = 1, seed_size
      seed(i) = i
    end do

    call random_seed( put = seed(:) )

  end subroutine

end program ${PROGRAM_NAME}$
