#:include '../src/real_kinds.fypp'
#:set PROGRAM_NAME = 'check_dp_2_dx'
program ${PROGRAM_NAME}$

  use, intrinsic :: iso_fortran_env, only: error_unit
  #:for REAL_KIND in REAL_KINDS
  use, intrinsic :: iso_fortran_env, only: ${REAL_KIND}$
  #:endfor

  use, intrinsic :: ieee_arithmetic, only: ieee_next_after

  use, non_intrinsic :: legendre_polynomial_recurrence_fortran

  use, non_intrinsic :: test_utilities



  implicit none



  integer, parameter :: num_trials = 10000



  #:for REAL_KIND in REAL_KINDS
  call ${PROGRAM_NAME}$_${REAL_KIND}$()
  #:endfor

  print *, 'OK: ${PROGRAM_NAME}$'



  contains


  #:for REAL_KIND in REAL_KINDS

  #:set SUBROUTINE_NAME = PROGRAM_NAME + '_' + REAL_KIND
  subroutine ${SUBROUTINE_NAME}$()

    integer :: i

    real(${REAL_KIND}$) :: dp_2_dx

    real(${REAL_KIND}$) :: dp_2_dx_ref, dp_2_dx_ref_next_after, dp_2_dx_ref_next_before

    real(${REAL_KIND}$) :: x

    type(legendre_polynomial_with_derivative_${REAL_KIND}$_type) :: lp


    call initialize_prng

    call lp%set(2)


    do i = 1, num_trials

      call random_number(x) ! [0, 1)

      x = 2.0_${REAL_KIND}$ * x - 1.0_${REAL_KIND}$ ! [-1, 1)

      dp_2_dx_ref = 3.0_${REAL_KIND}$ * x

      dp_2_dx_ref_next_after  = ieee_next_after(dp_2_dx_ref, dp_2_dx_ref + 1.0_${REAL_KIND}$)
      dp_2_dx_ref_next_before = ieee_next_after(dp_2_dx_ref, dp_2_dx_ref - 1.0_${REAL_KIND}$)

      call lp%set(x)

      call lp%evaluate()

      dp_2_dx = lp%dp_n_dx()

      if (dp_2_dx < dp_2_dx_ref_next_before) then

        write(error_unit, *) 'x                                    : ', x
        write(error_unit, *) 'ieee_next_after  ( dp_2_dx_ref (x) ) : ', dp_2_dx_ref_next_after
        write(error_unit, *) '                   dp_2_dx     (x)   : ', dp_2_dx
        write(error_unit, *) 'ieee_next_before ( dp_2_dx_ref (x) ) : ', dp_2_dx_ref_next_before
        write(error_unit, *) 'dp_2_dx was less than the reference.'

        error stop

      else if (dp_2_dx > dp_2_dx_ref_next_after) then

        write(error_unit, *) 'x                                    : ', x
        write(error_unit, *) 'ieee_next_after  ( dp_2_dx_ref (x) ) : ', dp_2_dx_ref_next_after
        write(error_unit, *) '                   dp_2_dx     (x)   : ', dp_2_dx
        write(error_unit, *) 'ieee_next_before ( dp_2_dx_ref (x) ) : ', dp_2_dx_ref_next_before
        write(error_unit, *) 'dp_2_dx was greater than the reference.'

        error stop

      end if

    end do

  end subroutine ${SUBROUTINE_NAME}$
  #:del SUBROUTINE_NAME

  #:endfor
end program ${PROGRAM_NAME}$
