#:include '../src/real_kinds.fypp'
#:set PROGRAM_NAME = 'check_dp_3_dx'
program ${PROGRAM_NAME}$

  use, intrinsic :: iso_fortran_env, only: error_unit
  #:for REAL_KIND in REAL_KINDS
  use, intrinsic :: iso_fortran_env, only: ${REAL_KIND}$
  #:endfor

  use, intrinsic :: ieee_arithmetic, only: ieee_next_after

  use, non_intrinsic :: legendre_polynomial_recurrence_fortran

  use, non_intrinsic :: test_utilities



  implicit none



  integer, parameter :: num_trials = 10000



  #:for REAL_KIND in REAL_KINDS
  call ${PROGRAM_NAME}$_${REAL_KIND}$()
  #:endfor

  print *, 'OK: ${PROGRAM_NAME}$'



  contains


  #:for REAL_KIND in REAL_KINDS

  #:set SUBROUTINE_NAME = PROGRAM_NAME + '_' + REAL_KIND
  subroutine ${SUBROUTINE_NAME}$()

    real(${REAL_KIND}$), parameter :: rel_tol = epsilon(1.0_${REAL_KIND}$) * 4.0_${REAL_KIND}$


    integer :: i

    real(${REAL_KIND}$) :: dp_3_dx, dp_3_dx_ref, abs_dp_3_dx_dif

    real(${REAL_KIND}$) :: tolerance

    real(${REAL_KIND}$) :: x

    type(legendre_polynomial_with_derivative_${REAL_KIND}$_type) :: lp


    call initialize_prng

    call lp%set(3)


    do i = 1, num_trials

      call random_number(x) ! [0, 1)

      x = 2.0_${REAL_KIND}$ * x - 1.0_${REAL_KIND}$ ! [-1, 1)

      dp_3_dx_ref = 0.5_${REAL_KIND}$ * (15.0_${REAL_KIND}$ * x * x - 3.0_${REAL_KIND}$)

      call lp%set(x)

      call lp%evaluate()

      dp_3_dx = lp%dp_n_dx()

      abs_dp_3_dx_dif = abs(dp_3_dx - dp_3_dx_ref)
      tolerance   = rel_tol * max(abs(dp_3_dx_ref), 1.0_${REAL_KIND}$)

      if (abs_dp_3_dx_dif > tolerance) then

        write(error_unit, *) 'x               : ', x
        write(error_unit, *) 'dp_3_dx     (x) : ', dp_3_dx
        write(error_unit, *) 'dp_3_dx_ref (x) : ', dp_3_dx_ref
        write(error_unit, *) 'diff            : ', abs_dp_3_dx_dif
        write(error_unit, *) 'tolerance       : ', tolerance
        write(error_unit, *) 'dp_3_dx differs from the reference beyond the tolerance.'

        error stop

      end if

    end do

  end subroutine ${SUBROUTINE_NAME}$
  #:del SUBROUTINE_NAME

  #:endfor
end program ${PROGRAM_NAME}$
