#:include '../src/real_kinds.fypp'
#:set PROGRAM_NAME = 'check_unset_x'
program ${PROGRAM_NAME}$

  use, intrinsic :: iso_fortran_env, only: error_unit
  #:for REAL_KIND in REAL_KINDS
  use, intrinsic :: iso_fortran_env, only: ${REAL_KIND}$
  #:endfor

  use, intrinsic :: ieee_arithmetic, only: ieee_is_nan

  use, non_intrinsic :: legendre_polynomial_recurrence_fortran

  use, non_intrinsic :: test_utilities, only: initialize_prng, is_one, is_zero



  implicit none



  integer, parameter, dimension(19) :: list_degree = &!
    [ &!
           1,  2,  3,  4,  5,  6,  7,  8,  9, &!
      10, 11, 22, 33, 44, 55, 66, 77, 88, 99  &!
    ]


  #:for REAL_KIND in REAL_KINDS
  call ${PROGRAM_NAME}$_deg_plus_${REAL_KIND}$()
  call ${PROGRAM_NAME}$_deg_zero_${REAL_KIND}$()

  #:endfor
  print *, 'OK: ${PROGRAM_NAME}$'



  contains


  #:for REAL_KIND in REAL_KINDS

  #:set SUBROUTINE_NAME = PROGRAM_NAME + '_deg_plus_' + REAL_KIND
  subroutine ${SUBROUTINE_NAME}$()

    integer :: i_degree

    real(${REAL_KIND}$) :: p_n, dp_n_dx

    type(legendre_polynomial_${REAL_KIND}$_type) :: lp

    type(legendre_polynomial_with_derivative_${REAL_KIND}$_type) :: lp_with_derivative


    do i_degree = 1, size( list_degree(:) )

      call lp                 % set( list_degree(i_degree) )
      call lp_with_derivative % set( list_degree(i_degree) )

      ! call lp                 % set(x) ! unset
      ! call lp_with_derivative % set(x) ! unset

      call lp                 % evaluate()
      call lp_with_derivative % evaluate()


      p_n = lp%p_n()

      if ( .not. ieee_is_nan(p_n) ) then

        write(error_unit, *) 'degree : ', list_degree(i_degree)
        write(error_unit, *) 'p_n    : ', p_n
        write(error_unit, *) 'p_n must be NaN.'

        error stop

      end if


      p_n = lp_with_derivative%p_n()

      if ( .not. ieee_is_nan(p_n) ) then

        write(error_unit, *) 'degree : ', list_degree(i_degree)
        write(error_unit, *) 'p_n    : ', p_n
        write(error_unit, *) 'p_n must be NaN.'

        error stop

      end if


      dp_n_dx = lp_with_derivative%dp_n_dx()

      if ( list_degree(i_degree) > 1 ) then

        if ( .not. ieee_is_nan(dp_n_dx) ) then

          write(error_unit, *) 'degree  : ', list_degree(i_degree)
          write(error_unit, *) 'dp_n_dx : ', dp_n_dx
          write(error_unit, *) 'dp_n_dx must be NaN.'

          error stop

        end if

      else

        if ( .not. is_one(dp_n_dx) ) then

          write(error_unit, *) 'dp_1_dx : ', dp_n_dx
          write(error_unit, *) 'dp_1_dx was less than 1.'

          error stop

        end if

      end if

    end do

  end subroutine ${SUBROUTINE_NAME}$
  #:del SUBROUTINE_NAME

  #:endfor


  #:for REAL_KIND in REAL_KINDS

  #:set SUBROUTINE_NAME = PROGRAM_NAME + '_deg_zero_' + REAL_KIND
  subroutine ${SUBROUTINE_NAME}$()

    real(${REAL_KIND}$) :: p_0, dp_0_dx

    type(legendre_polynomial_${REAL_KIND}$_type) :: lp

    type(legendre_polynomial_with_derivative_${REAL_KIND}$_type) :: lp_with_derivative


    call lp                 % set(0)
    call lp_with_derivative % set(0)

    ! call lp                 % set(x) ! unset
    ! call lp_with_derivative % set(x) ! unset

    call lp                 % evaluate()
    call lp_with_derivative % evaluate()


    p_0 = lp%p_n()

    if ( .not. is_one(p_0) ) then

      write(error_unit, *) 'p_0 : ', p_0
      write(error_unit, *) 'p_0 must be 1.'

      error stop

    end if


    p_0 = lp_with_derivative%p_n()

    if ( .not. is_one(p_0) ) then

      write(error_unit, *) 'p_0 : ', p_0
      write(error_unit, *) 'p_0 must be 1.'

      error stop

    end if


    dp_0_dx = lp_with_derivative%dp_n_dx()

    if ( .not. is_zero(dp_0_dx) ) then

      write(error_unit, *) 'dp_0_dx : ', dp_0_dx
      write(error_unit, *) 'dp_0_dx must be 0.'

      error stop

    end if

  end subroutine ${SUBROUTINE_NAME}$
  #:del SUBROUTINE_NAME

  #:endfor
end program ${PROGRAM_NAME}$
