#:include '../src/real_kinds.fypp'
#:set PROGRAM_NAME = 'check_dp_2_dx'
program ${PROGRAM_NAME}$

  use, intrinsic :: iso_fortran_env, only: error_unit
  #:for REAL_KIND in REAL_KINDS
  use, intrinsic :: iso_fortran_env, only: ${REAL_KIND}$
  #:endfor

  use, non_intrinsic :: legendre_polynomial_recurrence_fortran

  use, non_intrinsic :: test_utilities, only: initialize_prng, is_equal



  implicit none



  integer, parameter :: num_trials = 10000



  #:for REAL_KIND in REAL_KINDS
  call ${PROGRAM_NAME}$_${REAL_KIND}$()
  #:endfor

  print *, 'OK: ${PROGRAM_NAME}$'



  contains


  #:for REAL_KIND in REAL_KINDS

  #:set SUBROUTINE_NAME = PROGRAM_NAME + '_' + REAL_KIND
  subroutine ${SUBROUTINE_NAME}$()

    integer :: i

    real(${REAL_KIND}$) :: dp_2_dx, dp_2_dx_ref, x

    type(legendre_polynomial_with_derivative_${REAL_KIND}$_type) :: lp


    call initialize_prng

    call lp%set(2)


    do i = 1, num_trials

      call random_number(x) ! [0, 1)

      x = 2.0_${REAL_KIND}$ * x - 1.0_${REAL_KIND}$ ! [-1, 1)

      dp_2_dx_ref = 3.0_${REAL_KIND}$ * x

      call lp%set(x)

      call lp%evaluate()

      dp_2_dx = lp%dp_n_dx()

      if ( .not. is_equal(dp_2_dx, dp_2_dx_ref) ) then

        write(error_unit, *) '             x  : ', x
        write(error_unit, *) 'dp_2_dx     (x) : ', dp_2_dx
        write(error_unit, *) 'dp_2_dx_ref (x) : ', dp_2_dx_ref
        write(error_unit, *) 'dp_2_dx must be equal to dp_2_dx_ref.'

        error stop

      end if

    end do

  end subroutine ${SUBROUTINE_NAME}$
  #:del SUBROUTINE_NAME

  #:endfor
end program ${PROGRAM_NAME}$
