#:include '../src/real_kinds.fypp'
#:set PROGRAM_NAME = 'check_dp_1_dx'
program ${PROGRAM_NAME}$

  use, intrinsic :: iso_fortran_env, only: error_unit
  #:for REAL_KIND in REAL_KINDS
  use, intrinsic :: iso_fortran_env, only: ${REAL_KIND}$
  #:endfor

  use, intrinsic :: ieee_arithmetic, only: ieee_next_after

  use, non_intrinsic :: legendre_polynomial_recurrence_fortran

  use, non_intrinsic :: test_utilities



  implicit none



  integer, parameter :: num_trials = 100


  #:for REAL_KIND in REAL_KINDS

  call ${PROGRAM_NAME}$_${REAL_KIND}$( &!
    one_next_before = ieee_next_after(1.0_${REAL_KIND}$, 0.0_${REAL_KIND}$) , &!
    one_next_after  = ieee_next_after(1.0_${REAL_KIND}$, 2.0_${REAL_KIND}$)   &!
  )

  #:endfor

  print *, 'OK: ${PROGRAM_NAME}$'



  contains


  #:for REAL_KIND in REAL_KINDS

  #:set SUBROUTINE_NAME = PROGRAM_NAME + '_' + REAL_KIND
  subroutine ${SUBROUTINE_NAME}$(one_next_before, one_next_after)

    real(${REAL_KIND}$), intent(in) :: one_next_before, one_next_after


    integer :: i

    real(${REAL_KIND}$) :: dp_1_dx, x

    type(legendre_polynomial_with_derivative_${REAL_KIND}$_type) :: lp


    call initialize_prng

    call lp%set(1)


    do i = 1, num_trials

      call random_number(x) ! [0, 1)

      x = 2.0_${REAL_KIND}$ * x - 1.0_${REAL_KIND}$ ! [-1, 1)

      call lp%set(x)

      call lp%evaluate()

      dp_1_dx = lp%dp_n_dx()

      if (dp_1_dx < one_next_before) then

        write(error_unit, *) 'x                     : ', x
        write(error_unit, *) 'ieee_next_after  (1)  : ', one_next_after
        write(error_unit, *) 'dp_1_dx               : ', dp_1_dx
        write(error_unit, *) 'ieee_next_before (1)  : ', one_next_before
        write(error_unit, *) 'dp_1_dx was less than 1.'

        error stop

      else if (dp_1_dx > one_next_after) then

        write(error_unit, *) 'x                     : ', x
        write(error_unit, *) 'ieee_next_after  (1)  : ', one_next_after
        write(error_unit, *) 'dp_1_dx               : ', dp_1_dx
        write(error_unit, *) 'ieee_next_before (1)  : ', one_next_before
        write(error_unit, *) 'dp_1_dx was greater than 1.'

        error stop

      end if

    end do

  end subroutine ${SUBROUTINE_NAME}$
  #:del SUBROUTINE_NAME

  #:endfor
end program ${PROGRAM_NAME}$
