#:include '../src/real_kinds.fypp'
#:set PROGRAM_NAME = 'check_p_2'
program ${PROGRAM_NAME}$

  use, intrinsic :: iso_fortran_env, only: error_unit
  #:for REAL_KIND in REAL_KINDS
  use, intrinsic :: iso_fortran_env, only: ${REAL_KIND}$
  #:endfor

  use, intrinsic :: ieee_arithmetic, only: ieee_next_after

  use, non_intrinsic :: legendre_polynomial_recurrence_fortran



  implicit none



  integer, parameter :: num_trials = 10000



  #:for REAL_KIND in REAL_KINDS
  call ${PROGRAM_NAME}$_${REAL_KIND}$()
  #:endfor

  print *, 'OK: ${PROGRAM_NAME}$'



  contains


  #:for REAL_KIND in REAL_KINDS

  #:set SUBROUTINE_NAME = PROGRAM_NAME + '_' + REAL_KIND
  subroutine ${SUBROUTINE_NAME}$()

    integer :: i

    real(${REAL_KIND}$) :: p_2

    real(${REAL_KIND}$) :: p_2_ref, p_2_ref_next_after, p_2_ref_next_before

    real(${REAL_KIND}$) :: x

    type(legendre_polynomial_${REAL_KIND}$_type) :: lp


    call initialize_prng

    call lp%set(2)


    do i = 1, num_trials

      call random_number(x) ! [0, 1)

      x = 2.0_${REAL_KIND}$ * x - 1.0_${REAL_KIND}$ ! [-1, 1)

      p_2_ref = 0.5_${REAL_KIND}$ * (3.0_${REAL_KIND}$ * x * x - 1.0_${REAL_KIND}$)

      p_2_ref_next_after  = ieee_next_after(p_2_ref, p_2_ref + 1.0_${REAL_KIND}$)
      p_2_ref_next_before = ieee_next_after(p_2_ref, p_2_ref - 1.0_${REAL_KIND}$)

      call lp%set(x)

      call lp%evaluate()

      p_2 = lp%p_n()

      if (p_2 < p_2_ref_next_before) then

        write(error_unit, *) 'x           : ', x
        write(error_unit, *) 'p_2     (x) : ', p_2
        write(error_unit, *) 'p_2_ref (x) : ', p_2_ref
        write(error_unit, *) 'p_2 was less than the reference.'

        error stop

      else if (p_2 > p_2_ref_next_after) then

        write(error_unit, *) 'x           : ', x
        write(error_unit, *) 'p_2     (x) : ', p_2
        write(error_unit, *) 'p_2_ref (x) : ', p_2_ref
        write(error_unit, *) 'p_2 was greater than the reference.'

        error stop

      end if

    end do

  end subroutine ${SUBROUTINE_NAME}$
  #:del SUBROUTINE_NAME

  #:endfor


  subroutine initialize_prng

    integer :: i, seed_size

    integer, allocatable :: seed(:)

    call random_seed(size=seed_size)

    allocate( seed(seed_size) )

    do i = 1, seed_size
      seed(i) = i
    end do

    call random_seed( put = seed(:) )

  end subroutine

end program ${PROGRAM_NAME}$
