#:include '../src/real_kinds.fypp'
#:set PROGRAM_NAME = 'check_p_1'
program ${PROGRAM_NAME}$

  use, intrinsic :: iso_fortran_env, only: error_unit
  #:for REAL_KIND in REAL_KINDS
  use, intrinsic :: iso_fortran_env, only: ${REAL_KIND}$
  #:endfor

  use, intrinsic :: ieee_arithmetic, only: ieee_next_after

  use, non_intrinsic :: legendre_polynomial_recurrence_fortran

  use, non_intrinsic :: test_utilities



  implicit none



  integer, parameter :: num_trials = 100



  #:for REAL_KIND in REAL_KINDS
  call ${PROGRAM_NAME}$_${REAL_KIND}$()
  #:endfor

  print *, 'OK: ${PROGRAM_NAME}$'



  contains


  #:for REAL_KIND in REAL_KINDS

  #:set SUBROUTINE_NAME = PROGRAM_NAME + '_' + REAL_KIND
  subroutine ${SUBROUTINE_NAME}$()

    integer :: i

    real(${REAL_KIND}$) :: p_1, x, x_next_after, x_next_before

    type(legendre_polynomial_${REAL_KIND}$_type) :: lp


    call initialize_prng

    call lp%set(1)


    do i = 1, num_trials

      call random_number(x) ! [0, 1)

      x = 2.0_${REAL_KIND}$ * x - 1.0_${REAL_KIND}$ ! [-1, 1)

      x_next_after  = ieee_next_after(x, x + 1.0_${REAL_KIND}$)
      x_next_before = ieee_next_after(x, x - 1.0_${REAL_KIND}$)

      call lp%set(x)

      call lp%evaluate()

      p_1 = lp%p_n()

      if (p_1 < x_next_before) then

        write(error_unit, *) 'x                    : ', x
        write(error_unit, *) 'ieee_next_after  (x) : ', x_next_after
        write(error_unit, *) 'p_1              (x) : ', p_1
        write(error_unit, *) 'ieee_next_before (x) : ', x_next_before
        write(error_unit, *) 'p_1 was less than x.'

        error stop

      else if (p_1 > x_next_after) then

        write(error_unit, *) 'x                    : ', x
        write(error_unit, *) 'ieee_next_after  (x) : ', x_next_after
        write(error_unit, *) 'p_1              (x) : ', p_1
        write(error_unit, *) 'ieee_next_before (x) : ', x_next_before
        write(error_unit, *) 'p_1 was greater than x.'

        error stop

      end if

    end do

  end subroutine ${SUBROUTINE_NAME}$
  #:del SUBROUTINE_NAME

  #:endfor
end program ${PROGRAM_NAME}$
